# Generated by Django 4.0.4 on 2022-06-14 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('namche', '0003_alter_room_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('position', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
