# Generated by Django 4.0.4 on 2022-06-15 14:13

from django.db import migrations, models
import namche.models


class Migration(migrations.Migration):

    dependencies = [
        ('namche', '0006_food'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name=namche.models.Room)),
                ('date_from', models.DateTimeField()),
                ('date_to', models.DateTimeField()),
                ('adult', models.IntegerField()),
            ],
        ),
    ]
