# Generated by Django 4.0.4 on 2022-06-15 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('namche', '0011_rename_username_booking_username_alter_booking_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='personname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
