# Generated by Django 4.0.4 on 2022-06-15 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('namche', '0012_booking_personname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='username',
        ),
    ]
