# Generated by Django 4.0.4 on 2022-06-15 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('namche', '0013_remove_booking_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='name',
        ),
        migrations.AddField(
            model_name='booking',
            name='roomname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
