# Generated by Django 4.0.4 on 2022-06-15 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('namche', '0014_remove_booking_name_booking_roomname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='adult',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='date_from',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='date_to',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='personname',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='roomname',
        ),
        migrations.AddField(
            model_name='booking',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='message',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='phone',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='uname',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
