# Generated by Django 4.0.4 on 2022-06-16 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('namche', '0016_booking_adult_booking_date_from_booking_date_to_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='roomname',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
