# Generated by Django 4.0.4 on 2022-06-16 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('namche', '0017_alter_booking_roomname'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='s_phone',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
