# Generated by Django 4.0.4 on 2022-06-16 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('namche', '0021_alter_booking_phone_alter_booking_roomname'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Videos',
        ),
    ]
